//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CA.WorkFlow.UI.CreationOrder2 {
    
    
    public partial class DataView {
        
        /// <summary>
        /// Order_Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuickFlow.UI.ListForm.FormField Order_Number;
        
        /// <summary>
        /// Internal_Order_Type control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuickFlow.UI.ListForm.FormField Internal_Order_Type;
        
        /// <summary>
        /// Description control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuickFlow.UI.ListForm.FormField Description;
        
        /// <summary>
        /// Business_Area control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuickFlow.UI.ListForm.FormField Business_Area;
        
        /// <summary>
        /// Origin_Value control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuickFlow.UI.ListForm.FormField Origin_Value;
        
        /// <summary>
        /// Effective_Date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuickFlow.UI.ListForm.FormField Effective_Date;
        
        /// <summary>
        /// Expired_Date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuickFlow.UI.ListForm.FormField Expired_Date;
        
        /// <summary>
        /// attacthment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuickFlow.UI.ListForm.FormAttachments attacthment;
    }
}
